name: flatsync
description: SplitEasy - Split expenses easily with friends and roommates
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Database
  isar: ^3.1.0
  isar_flutter_libs:

  # State Management
  provider: ^6.0.0

  # Networking & API
  dio: ^5.4.0
  connectivity_plus: ^5.0.0
  http: ^1.1.0
  uuid: ^4.0.0

  # Authentication & Security
  flutter_secure_storage: ^9.0.0

  # contacts_service: ^0.6.3
  flutter_contacts: ^1.1.7+1
  permission_handler: ^11.3.1

  # UI & Theme
  google_fonts: ^6.1.0
  intl_phone_field: ^3.2.0
  
  # Firebase
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0

  # Security
  crypto: ^3.0.3

  # Utilities
  intl: ^0.19.0
  device_info_plus: ^9.0.0
  csv: ^5.1.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.0
  share_plus: ^7.0.0
  shared_preferences: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  isar_generator: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # see https://flutter.dev/to/font-from-package
