name: flatsync
description: SettleFlow - Split expenses easily with friends and roommates
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Database
  isar_community: ^3.3.2
  isar_community_flutter_libs:

  # State Management
  provider: ^6.0.0

  # Networking & API
  dio: ^5.4.0
  connectivity_plus: ^5.0.0
  uuid: ^4.0.0

  # Authentication & Security
  flutter_secure_storage: ^9.0.0

  # contacts_service: ^0.6.3
  flutter_contacts: ^1.1.7+1
  permission_handler: ^11.3.1

  # UI & Theme
  google_fonts: ^6.1.0
  intl_phone_field: ^3.2.0

  # Firebase
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0

  # Security
  crypto: ^3.0.3
  local_auth: ^2.3.0

  in_app_update: ^4.2.3

  # Utilities
  intl: ^0.19.0
  timezone: ^0.9.0
  device_info_plus: ^9.0.0
  csv: ^5.1.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.0
  share_plus: ^7.0.0
  shared_preferences: ^2.0.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  isar_community_generator: ^3.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # see https://flutter.dev/to/font-from-package

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
